<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>329150da-5a89-409d-94be-570eff81231c</UserSecretsId>
		<!--<EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
		<CompilerGeneratedFilesOutputPath>Generated</CompilerGeneratedFilesOutputPath>-->
	</PropertyGroup>

	<ItemGroup>
	  <Content Remove="wwwroot\js\app._hs" />
	</ItemGroup>

	<ItemGroup>
	  <None Remove="Kits\Anchors\anchors.css" />
	  <None Remove="Kits\Buttons\buttons.css" />
	  <None Remove="Kits\Effects\shadows.css" />
	  <None Remove="Kits\Icons\icons.css" />
	  <None Remove="Kits\Inputs\inputs.css" />
	  <None Remove="Kits\Lists\lists.css" />
	  <None Remove="Kits\Shared\destyle-reset.css" />
	  <None Remove="Kits\Typography\typography.css" />
	</ItemGroup>

	<ItemGroup>
	  <_ContentIncludedByDefault Remove="wwwroot\js\app._hs" />
	</ItemGroup>

	<ItemGroup>
	  <Content Include="Kits\Anchors\anchors.css">
	    <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
	  </Content>
	  <Content Include="Kits\Buttons\buttons.css">
	    <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
	  </Content>
	  <Content Include="Kits\Effects\shadows.css">
	    <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
	  </Content>
	  <Content Include="Kits\Icons\icons.css">
	    <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
	  </Content>
	  <Content Include="Kits\Inputs\inputs.css">
	    <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
	  </Content>
	  <Content Include="Kits\Lists\lists.css">
	    <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
	  </Content>
	  <Content Include="Kits\Shared\destyle-reset.css">
	    <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
	  </Content>
	  <Content Include="Kits\Typography\typography.css">
	    <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
	  </Content>
	</ItemGroup>

	<ItemGroup>
	  <None Include="wwwroot\js\app._hs" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="SharpScss" Version="2.0.0" />
		<!--<PackageReference Include="Sparc.Blossom" Version="8.0.2" />-->
		<PackageReference Include="Sparc.Blossom.Data.Cosmos" Version="8.0.0" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\Sparc.Kernel\Sparc.Blossom.Server.ApiGenerator\Sparc.Blossom.ApiGenerator.csproj" OutputItemType="Analyzer" />
	  <ProjectReference Include="..\..\Sparc.Kernel\Sparc.Blossom.Server\Sparc.Blossom.csproj" />
	</ItemGroup>
</Project>